version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/processing:/app/processing
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Mount paths for Docker-in-Docker
      - HOST_UPLOAD_PATH=${PWD}/backend/uploads
      - HOST_PROCESSING_PATH=${PWD}/backend/processing
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/processing:/app/processing
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Use our custom COLMAP image with MKL support
      - COLMAP_IMAGE=colmap-cpu:latest
      # Mount paths for Docker-in-Docker
      - HOST_UPLOAD_PATH=${PWD}/backend/uploads
      - HOST_PROCESSING_PATH=${PWD}/backend/processing
    depends_on:
      - redis
    command: celery -A tasks worker --loglevel=info

volumes:
  redis_data: 